import { gunzipSync } from 'zlib';
import {
  AnsibleContentManifest,
  CONTENT_MANIFEST_ARTIFACT_TYPE,
  isContentManifest,
} from '@ansible/content-model';
import { OCIClient } from './OCIClient';
import { Descriptor } from './types';

/**
 * Reads an Ansible content manifest published alongside an image.
 *
 * The manifest is produced at build time inside the execution environment and pushed as
 * a separate OCI artifact referring to the image. Reading it costs a few HTTP calls
 * rather than a multi-gigabyte pull, and — because it was generated by the image's own
 * ansible-core — it is exact rather than approximate.
 *
 * Two real-world wrinkles are handled here, both observed against a live registry:
 *
 *  - Discovery may not use the referrers API. Registries predating OCI 1.1 return 404
 *    from `/v2/<repo>/referrers/<digest>`, so the spec's tag fallback
 *    (`sha256-<hex>`) is used instead.
 *
 *  - The payload may not be raw JSON. Quay validates layer media types against a fixed
 *    allowlist and rejects custom artifact types, so publishers package the manifest as
 *    a standard gzipped tar layer. Both encodings are accepted here.
 */

/** Layer media types a content manifest may legitimately arrive as. */
const TAR_GZIP = 'application/vnd.oci.image.layer.v1.tar+gzip';
const TAR_PLAIN = 'application/vnd.oci.image.layer.v1.tar';

const TAR_BLOCK = 512;

/**
 * Extract one file from an uncompressed tar.
 *
 * A dependency-free reader is worth it here: the archive holds a single small JSON
 * document, and the alternative is pulling a tar library into a package that otherwise
 * has no runtime dependencies.
 */
export function extractFromTar(tar: Buffer, filename?: string): Buffer | undefined {
  let offset = 0;
  while (offset + TAR_BLOCK <= tar.length) {
    const header = tar.subarray(offset, offset + TAR_BLOCK);

    // Two consecutive zero blocks mark end-of-archive.
    if (header.every(byte => byte === 0)) return undefined;

    const name = header.subarray(0, 100).toString('utf8').replace(/\0.*$/, '').trim();
    const sizeField = header.subarray(124, 136).toString('utf8').replace(/\0.*$/, '').trim();
    const size = parseInt(sizeField, 8);
    if (!Number.isFinite(size) || size < 0) return undefined;

    const dataStart = offset + TAR_BLOCK;
    if (!filename || name === filename || name.endsWith(`/${filename}`)) {
      return tar.subarray(dataStart, dataStart + size);
    }
    // Entries are padded to a 512-byte boundary.
    offset = dataStart + Math.ceil(size / TAR_BLOCK) * TAR_BLOCK;
  }
  return undefined;
}

/**
 * Decode a layer blob into whatever JSON it carries.
 *
 * Handles the transport encodings a publisher may have used — raw JSON, gzip, or a
 * gzipped tar containing one file. Deliberately makes no judgement about the content:
 * unwrapping a layer is a registry concern, and recognising Ansible content is a
 * content-type concern.
 */
export function decodeLayerPayload(
  blob: Buffer,
  mediaType?: string,
  filename = 'content-manifest.json',
): unknown | undefined {
  let data = blob;

  if (mediaType === TAR_GZIP || (blob[0] === 0x1f && blob[1] === 0x8b)) {
    try {
      data = gunzipSync(blob);
    } catch {
      return undefined;
    }
  }

  if (mediaType === TAR_GZIP || mediaType === TAR_PLAIN || looksLikeTar(data)) {
    const extracted = extractFromTar(data, filename);
    if (extracted) data = extracted;
  }

  try {
    return JSON.parse(data.toString('utf8'));
  } catch {
    return undefined;
  }
}

/** Decode a layer blob and assert it really is an Ansible content manifest. */
export function decodeManifestBlob(
  blob: Buffer,
  mediaType?: string,
): AnsibleContentManifest | undefined {
  const parsed = decodeLayerPayload(blob, mediaType);
  return isContentManifest(parsed) ? parsed : undefined;
}

/** POSIX tar sets the `ustar` magic at offset 257. */
function looksLikeTar(data: Buffer): boolean {
  return (
    data.length > 265 && data.subarray(257, 262).toString('utf8').startsWith('ustar')
  );
}

export interface ContentManifestLocation {
  manifest: AnsibleContentManifest;
  /** How the referrer was discovered — records registry capability, not trivia. */
  via: 'native' | 'tag-fallback';
  referrerDigest: string;
}

/**
 * Locate and read the content manifest referring to an image.
 *
 * Returns undefined when no manifest is published — an expected state for images built
 * before manifest emission existed, not an error. Callers surface that as "contents
 * unknown" rather than as "contains nothing".
 */
export async function readContentManifest(
  client: OCIClient,
  repository: string,
  imageDigest: string,
): Promise<ContentManifestLocation | undefined> {
  const { referrers, via } = await client.getReferrers(repository, imageDigest);
  if (via === 'none' || referrers.length === 0) return undefined;

  const candidates = pickCandidates(referrers);

  for (const descriptor of candidates) {
    const blob = await fetchLayerBlob(client, repository, descriptor);
    if (!blob) continue;
    const manifest = decodeManifestBlob(blob.data, blob.mediaType);
    if (manifest) {
      return { manifest, via, referrerDigest: descriptor.digest };
    }
  }
  return undefined;
}

/**
 * Prefer referrers that declare the Ansible artifact type, but do not require it.
 *
 * Some registries drop or normalise `artifactType`, so a referrer without it may still
 * be the manifest. Declared matches are tried first; everything else is a fallback.
 */
function pickCandidates(referrers: Descriptor[]): Descriptor[] {
  const declared = referrers.filter(
    r => r.artifactType === CONTENT_MANIFEST_ARTIFACT_TYPE,
  );
  const rest = referrers.filter(r => r.artifactType !== CONTENT_MANIFEST_ARTIFACT_TYPE);
  return [...declared, ...rest];
}

async function fetchLayerBlob(
  client: OCIClient,
  repository: string,
  descriptor: Descriptor,
): Promise<{ data: Buffer; mediaType?: string } | undefined> {
  const artifact = await client
    .getManifest(repository, descriptor.digest)
    .catch(() => undefined);
  if (!artifact) return undefined;

  const layers = (artifact.manifest as { layers?: Descriptor[] }).layers;
  const layer = layers?.[0];
  if (!layer) return undefined;

  const buffer = await client.getBlob(repository, layer);
  if (!buffer) return undefined;
  return { data: buffer, mediaType: layer.mediaType };
}
