/**
 * Live end-to-end verification against a real registry.
 *
 * Proves the consumer half of build-time content discovery: given only a registry,
 * repository and tag, read the complete content inventory of an execution environment
 * without pulling the image.
 *
 * Skipped unless E2E_REGISTRY is set, so the normal suite stays hermetic:
 *
 *   E2E_REGISTRY=localhost:8080 E2E_REPOSITORY=demo/network-ee E2E_TAG=poc \
 *   E2E_USERNAME=... E2E_PASSWORD=... \
 *   yarn workspace @ansible/automation-content-common test liveRegistry
 */
import { CapabilityProbe } from './CapabilityProbe';
import { OCIClient } from './OCIClient';
import { readContentManifest } from './contentManifestReader';
import { RegistryConnection } from './types';

const registry = process.env.E2E_REGISTRY;
const repository = process.env.E2E_REPOSITORY ?? 'demo/network-ee';
const tag = process.env.E2E_TAG ?? 'poc';

const describeLive = registry ? describe : describe.skip;

describeLive('live registry end-to-end', () => {
  jest.setTimeout(180_000);

  const connection: RegistryConnection = {
    name: registry!,
    url: `http://${registry}`,
    auth: process.env.E2E_USERNAME
      ? {
          type: 'basic',
          username: process.env.E2E_USERNAME,
          password: process.env.E2E_PASSWORD,
        }
      : { type: 'anonymous' },
    repositories: [repository],
  };

  let client: OCIClient;
  beforeAll(() => {
    client = new OCIClient(connection);
  });

  it('probes registry capabilities', async () => {
    const caps = await new CapabilityProbe(client, {
      sampleRepository: repository,
    }).probe();

    // eslint-disable-next-line no-console
    console.log('\ncapabilities:', JSON.stringify(caps, null, 2));
    expect(caps.auth.length).toBeGreaterThan(0);
  });

  it('resolves the image tag to an immutable digest', async () => {
    const head = await client.headManifest(repository, tag);
    expect(head.status).toBe(200);
    expect(head.digest).toMatch(/^sha256:[0-9a-f]{64}$/);
  });

  it('reads the full content inventory without pulling the image', async () => {
    const head = await client.headManifest(repository, tag);
    const started = Date.now();
    const found = await readContentManifest(client, repository, head.digest!);
    const elapsedMs = Date.now() - started;

    expect(found).toBeDefined();
    const { manifest, via } = found!;

    const totals = manifest.collections.reduce(
      (acc, c) => {
        acc.plugins += c.plugins.length;
        acc.eda += c.edaPlugins.length;
        acc.rulebooks += c.rulebooks.length;
        for (const p of c.plugins) {
          acc.byType[p.type] = (acc.byType[p.type] ?? 0) + 1;
        }
        return acc;
      },
      { plugins: 0, eda: 0, rulebooks: 0, byType: {} as Record<string, number> },
    );

    /* eslint-disable no-console */
    console.log(`\ndiscovered via:  ${via}`);
    console.log(`read in:         ${elapsedMs} ms`);
    console.log(`generated by:    ${manifest.generatedBy.tool} ` +
      `(ansible-core ${manifest.generatedBy.ansibleCore}, ` +
      `docs=${manifest.generatedBy.docsSource})`);
    console.log(`collections:     ${manifest.collections.length}`);
    for (const c of manifest.collections) {
      console.log(`  ${c.namespace}.${c.name}:${c.version}  ` +
        `plugins=${c.plugins.length} eda=${c.edaPlugins.length} ` +
        `rulebooks=${c.rulebooks.length}`);
    }
    console.log(`totals:          ${totals.plugins} plugins ` +
      `(${Object.entries(totals.byType).map(([k, v]) => `${v} ${k}`).join(', ')}), ` +
      `${totals.eda} eda plugins, ${totals.rulebooks} rulebooks`);
    /* eslint-enable no-console */

    expect(manifest.collections.length).toBeGreaterThan(0);
    expect(totals.plugins).toBeGreaterThan(0);
  });

  it('carries fragment-resolved documentation, not just names', async () => {
    const head = await client.headManifest(repository, tag);
    const found = await readContentManifest(client, repository, head.digest!);
    const ios = found!.manifest.collections.find(c => c.name === 'ios');
    const vlans = ios?.plugins.find(p => p.name === 'ios_vlans');

    /* eslint-disable no-console */
    console.log(`\n${vlans?.fqcn}`);
    console.log(`  short:             ${vlans?.shortDescription}`);
    console.log(`  versionAdded:      ${vlans?.versionAdded}`);
    console.log(`  options:           ${Object.keys(vlans?.options ?? {}).join(', ')}`);
    console.log(`  config.suboptions: ` +
      `${Object.keys(vlans?.options?.config?.suboptions ?? {}).join(', ')}`);
    /* eslint-enable no-console */

    expect(vlans?.shortDescription).toBeTruthy();
    // Nested suboptions are where network resource module detail lives; their presence
    // is what distinguishes real extraction from a name listing.
    expect(Object.keys(vlans?.options?.config?.suboptions ?? {}).length).toBeGreaterThan(0);
    expect(vlans?.examples).toBeTruthy();
  });

  it('surfaces EDA plugin documentation, which ansible-doc cannot provide', async () => {
    const head = await client.headManifest(repository, tag);
    const found = await readContentManifest(client, repository, head.digest!);
    const eda = found!.manifest.collections.find(c => c.name === 'eda');
    const source = eda?.edaPlugins.find(p => p.name === 'alertmanager');

    /* eslint-disable no-console */
    console.log(`\n${source?.fqcn} (${source?.type})`);
    console.log(`  short:   ${source?.shortDescription}`);
    console.log(`  options: ${Object.keys(source?.options ?? {}).join(', ')}`);
    console.log(`\nkinds present: ` +
      `${[...new Set(eda?.edaPlugins.map(p => p.type))].join(', ')}`);
    /* eslint-enable no-console */

    expect(source?.shortDescription).toBeTruthy();
    expect(Object.keys(source?.options ?? {}).length).toBeGreaterThan(0);
  });
});
